interface url {
    [index: string]: string;
}

const BaseUri: string =
'/midas';
// 'https://manage.kmahjz.com.cn/midas';
export const urls: url = {
    BaseUri,
    captcha               : BaseUri + '/cap/get',
    heartbeat             : BaseUri + '/user/heart_beat',
    login                 : BaseUri + '/user/login',
    isLogged              : BaseUri + '/user/logged',
    logout                : BaseUri + '/user/logout',
    my_get                : BaseUri + '/my/get',
    my_set                : BaseUri + '/my/set',
    my_set_pass           : BaseUri + '/my/set_pass',
    upload_public         : BaseUri + '/uploader/public',
    upload_private        : BaseUri + '/uploader/private',
    getUserSideMenu       : BaseUri + '/user/getusersidemenu',
    admin_list            : BaseUri + '/admin/list',
    admin_all             : BaseUri + '/admin/all',
    admin_detail          : BaseUri + '/admin/detail',
    admin_add             : BaseUri + '/admin/add',
    admin_alter           : BaseUri + '/admin/alter',
    admin_delete          : BaseUri + '/admin/delete',
    admin_deleted         : BaseUri + '/admin/deleted',
    admin_deep_del        : BaseUri + '/admin/deep_del',
    admin_pass            : BaseUri + '/admin/pass',
    admin_rec             : BaseUri + '/admin/rec',
    group_list            : BaseUri + '/group/list',
    group_list_all        : BaseUri + '/group/all',
    group_detail          : BaseUri + '/group/detail',
    group_add             : BaseUri + '/group/add',
    group_alter           : BaseUri + '/group/alter',
    group_delete          : BaseUri + '/group/delete',
    rights_list           : BaseUri + '/group/rights',
    employee_list         : BaseUri + '/employee/list',
    employee_detail       : BaseUri + '/employee/detail',
    employee_search       : BaseUri + '/employee/search',
    employee_add          : BaseUri + '/employee/add',
    employee_alter        : BaseUri + '/employee/alter',
    employee_delete       : BaseUri + '/employee/delete',
    employee_deep_del     : BaseUri + '/employee/deep_del',
    employee_deleted      : BaseUri + '/employee/deleted',
    employee_rec          : BaseUri + '/employee/rec',
    services_list         : BaseUri + '/services/list',
    services_detail       : BaseUri + '/services/detail',
    services_add          : BaseUri + '/services/add',
    services_alter        : BaseUri + '/services/alter',
    services_delete       : BaseUri + '/services/delete',
    services_deep_del     : BaseUri + '/services/deep_del',
    services_deleted      : BaseUri + '/services/deleted',
    services_rec          : BaseUri + '/services/rec',
    services_category     : BaseUri + '/services/category',
    services_options      : BaseUri + '/services/options',
    services_opt_del      : BaseUri + '/services/opt_del',
    services_opt_add      : BaseUri + '/services/opt_add',
    services_opt_edit     : BaseUri + '/services/opt_edit',
    services_quick_edit   : BaseUri + '/services/quick_edit',
    services_quick_ch_cat : BaseUri + '/services/cat_quick_edit',
    services_cat_del      : BaseUri + '/services/cat_del',
    services_cat_name     : BaseUri + '/services/cat_name',
    customer_list         : BaseUri + '/customer/list',
    customer_other        : BaseUri + '/customer/other',
    customer_past         : BaseUri + '/customer/past',
    customer_search       : BaseUri + '/customer/search',
    customer_detail       : BaseUri + '/customer/detail',
    customer_history      : BaseUri + '/customer/history',
    customer_add          : BaseUri + '/customer/add',
    customer_alter        : BaseUri + '/customer/alter',
    customer_delete       : BaseUri + '/customer/delete',
    customer_deep_del     : BaseUri + '/customer/deep_del',
    customer_deleted      : BaseUri + '/customer/deleted',
    customer_rec          : BaseUri + '/customer/rec',
    customer_get_map      : BaseUri + '/customer/get_map',
    order_edit            : BaseUri + '/order/edit',
    order_recall          : BaseUri + '/order/recall',
    order_renew           : BaseUri + '/order/renew',
    order_add             : BaseUri + '/order/add',
    order_delete          : BaseUri + '/order/delete',
    order_alter           : BaseUri + '/order/alter',
    order_get_remain      : BaseUri + '/order/get_remain',
    order_get_emp         : BaseUri + '/order/get_emp',
    customer_quick_blk    : BaseUri + '/customer/quick_black',
    customer_quick_rec_blk: BaseUri + '/customer/quick_rec_black',
    login_qr              : BaseUri + '/user/wx_login',
    login_qr_is_scanned   : BaseUri + '/user/is_wx_scanned',
    login_qr_is_loggedin  : BaseUri + '/user/is_wx_loggedin',
};

export const version = '0.9.7';